[phases.setup]
nixPkgs = ["nodejs_22", "yarn"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = [
  "yarn workspace @lattice/core build",
  "yarn workspace @lattice/api build"
]

[start]
cmd = "node packages/api/dist/index.js"
